version: '3.3'

services:
  database:
    container_name: database
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo
      POSTGRES_USER: postgres
    network_mode: 'host'
